databases:
  - name: marketflow-db
    plan: free
    databaseName: store
    user: marketflow

services:
  - type: web
    name: marketflow-api
    runtime: python
    plan: free
    rootDir: backend
    buildCommand: ./build.sh
    startCommand: gunicorn config.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: CORS_ALLOWED_ORIGINS
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: marketflow-db
          property: connectionString
      - key: CELERY_TASK_ALWAYS_EAGER
        value: "true"
      - key: PYTHON_VERSION
        value: "3.12.8"
