# Generated by Django 5.1.7 on 2026-03-31 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_initial'),
        ('sellers', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='offer_group',
            field=models.SlugField(blank=True, max_length=140),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['offer_group', 'is_active'], name='products_pr_offer_g_d6a519_idx'),
        ),
    ]
