# Generated by Codex on 2026-04-02

from django.db import migrations, models


def assign_primary_offers(apps, schema_editor):
    Product = apps.get_model("products", "Product")

    Product.objects.update(is_primary_offer=False)

    offer_groups = (
        Product.objects.exclude(offer_group="")
        .values_list("offer_group", flat=True)
        .distinct()
    )

    for offer_group in offer_groups:
        primary = (
            Product.objects.filter(offer_group=offer_group)
            .order_by("-is_active", "price", "-purchases_count", "-views_count", "created_at", "pk")
            .first()
        )
        if primary:
            Product.objects.filter(pk=primary.pk).update(is_primary_offer=True)

    standalone_ids = Product.objects.filter(offer_group="").values_list("pk", flat=True)
    if standalone_ids:
        Product.objects.filter(pk__in=standalone_ids).update(is_primary_offer=True)


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_product_offer_group_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_primary_offer",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["offer_group", "is_primary_offer", "is_active"], name="products_pr_offer_g_7f16d9_idx"),
        ),
        migrations.RunPython(assign_primary_offers, migrations.RunPython.noop),
    ]
