apiVersion: apps/v1
kind: Deployment
metadata:
  name: marketflow-backend
  labels:
    app: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: my-registry/marketflow-backend:latest
        ports:
        - containerPort: 8000
        env:
        - name: DB_HOST
          value: "postgres-service"
        - name: DB_NAME
          value: "store"
        - name: DB_USER
          value: "postgres"
        - name: DB_PASSWORD
          value: "8747"
        - name: REDIS_URL
          value: "redis://redis-service:6379/0"
        - name: CELERY_BROKER_URL
          value: "redis://redis-service:6379/0"
